import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import Wedding from '../models/Wedding.js';
import Guest from '../models/Guest.js';
import Logistics from '../models/Logistics.js';

class ReportService {
  // Generate PDF Report
  async generatePDFReport(weddingId, userId) {
    try {
      const wedding = await Wedding.findOne({ _id: weddingId, user: userId });
      if (!wedding) throw new Error('Wedding not found');

      const guests = await Guest.find({ weddingId, createdBy: userId });
      const logistics = await Logistics.findOne({ weddingId, createdBy: userId });

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      
      // Header
      doc.fontSize(25).font('Helvetica-Bold')
         .text('BudgetBandhan', { align: 'center' })
         .fontSize(12).font('Helvetica')
         .text('Wedding Budget Report', { align: 'center' })
         .moveDown();

      // Wedding Details
      doc.fontSize(14).font('Helvetica-Bold').text('Wedding Details');
      doc.fontSize(10).font('Helvetica')
         .text(`Couple: ${wedding.coupleNames}`)
         .text(`Date: ${new Date(wedding.weddingDate).toLocaleDateString('en-IN')}`)
         .text(`Location: ${wedding.city} - ${wedding.venueTier.replace(/-/g, ' ')}`)
         .text(`Guests: ${wedding.guestCount} (${wedding.outstationPercentage}% outstation)`)
         .moveDown();

      // Budget Summary
      doc.fontSize(14).font('Helvetica-Bold').text('Budget Summary');
      
      // Create a table for budget
      const tableTop = doc.y;
      const itemX = 50;
      const amountX = 300;
      
      doc.fontSize(10).font('Helvetica-Bold');
      doc.text('Item', itemX, tableTop);
      doc.text('Amount', amountX, tableTop);
      
      doc.fontSize(10).font('Helvetica');
      let y = tableTop + 20;
      
      // Base Budget
      doc.text('Base Wedding Budget', itemX, y);
      doc.text(this.formatCurrency(wedding.budgetRanges?.medium || 0), amountX, y);
      y += 20;
      
      // Decor
      if (wedding.selectedDecor?.length > 0) {
        const decorTotal = wedding.selectedDecor.reduce((sum, d) => sum + (d.estimatedCost || 0), 0);
        doc.text('Decor', itemX, y);
        doc.text(this.formatCurrency(decorTotal), amountX, y);
        y += 20;
      }
      
      // Artists
      if (wedding.selectedArtists?.length > 0) {
        const artistTotal = wedding.selectedArtists.reduce((sum, a) => sum + (a.estimatedCost || 0), 0);
        doc.text('Artists', itemX, y);
        doc.text(this.formatCurrency(artistTotal), amountX, y);
        y += 20;
      }
      
      // F&B
      if (wedding.totalFnBCost) {
        doc.text('Food & Beverage', itemX, y);
        doc.text(this.formatCurrency(wedding.totalFnBCost), amountX, y);
        y += 20;
      }
      
      // Logistics
      if (logistics?.totalCost) {
        doc.text('Logistics', itemX, y);
        doc.text(this.formatCurrency(logistics.totalCost), amountX, y);
        y += 20;
      }
      
      // Total
      y += 10;
      doc.fontSize(12).font('Helvetica-Bold');
      doc.text('TOTAL BUDGET', itemX, y);
      doc.text(this.formatCurrency(wedding.totalBudget?.total || 0), amountX, y);
      
      // Guest List Summary
      doc.moveDown(2);
      doc.fontSize(14).font('Helvetica-Bold').text('Guest Summary');
      doc.fontSize(10).font('Helvetica');
      
      const confirmedGuests = guests.filter(g => g.rsvpStatus === 'confirmed').length;
      const pendingGuests = guests.filter(g => g.rsvpStatus === 'pending').length;
      const declinedGuests = guests.filter(g => g.rsvpStatus === 'declined').length;
      
      doc.text(`Total Guests: ${guests.length}`);
      doc.text(`✅ Confirmed: ${confirmedGuests}`);
      doc.text(`⏳ Pending: ${pendingGuests}`);
      doc.text(`❌ Declined: ${declinedGuests}`);
      
      // Footer
      doc.moveDown(3);
      doc.fontSize(8).text('Generated by BudgetBandhan', { align: 'center' });
      doc.text(new Date().toLocaleString(), { align: 'center' });
      
      return doc;
    } catch (error) {
      throw error;
    }
  }

  // Generate Excel Report
  async generateExcelReport(weddingId, userId) {
    try {
      const wedding = await Wedding.findOne({ _id: weddingId, user: userId });
      if (!wedding) throw new Error('Wedding not found');

      const guests = await Guest.find({ weddingId, createdBy: userId });
      const logistics = await Logistics.findOne({ weddingId, createdBy: userId });

      const workbook = new ExcelJS.Workbook();
      
      // Wedding Details Sheet
      const detailsSheet = workbook.addWorksheet('Wedding Details');
      detailsSheet.columns = [
        { header: 'Field', key: 'field', width: 30 },
        { header: 'Value', key: 'value', width: 40 }
      ];
      
      detailsSheet.addRows([
        { field: 'Couple Names', value: wedding.coupleNames },
        { field: 'Wedding Date', value: new Date(wedding.weddingDate).toLocaleDateString('en-IN') },
        { field: 'City', value: wedding.city },
        { field: 'Venue', value: wedding.venueTier.replace(/-/g, ' ') },
        { field: 'Total Guests', value: wedding.guestCount },
        { field: 'Outstation %', value: wedding.outstationPercentage + '%' },
        { field: 'Status', value: wedding.status }
      ]);

      // Budget Sheet
      const budgetSheet = workbook.addWorksheet('Budget Breakdown');
      budgetSheet.columns = [
        { header: 'Category', key: 'category', width: 30 },
        { header: 'Item', key: 'item', width: 40 },
        { header: 'Cost', key: 'cost', width: 20 }
      ];

      // Base Budget
      budgetSheet.addRow({ category: 'Base Budget', item: 'Venue + Catering', cost: wedding.budgetRanges?.medium || 0 });

      // Decor
      wedding.selectedDecor?.forEach(decor => {
        budgetSheet.addRow({ category: 'Decor', item: decor.name, cost: decor.estimatedCost || 0 });
      });

      // Artists
      wedding.selectedArtists?.forEach(artist => {
        budgetSheet.addRow({ category: 'Artist', item: artist.name, cost: artist.estimatedCost || 0 });
      });

      // F&B
      if (wedding.fnbSelection) {
        if (wedding.fnbSelection.mealPackages) {
          wedding.fnbSelection.mealPackages.forEach(meal => {
            budgetSheet.addRow({ category: 'F&B - Meals', item: meal.name, cost: meal.pricePerPerson * wedding.guestCount });
          });
        }
        if (wedding.fnbSelection.barPackage) {
          budgetSheet.addRow({ 
            category: 'F&B - Bar', 
            item: wedding.fnbSelection.barPackage.name, 
            cost: wedding.fnbSelection.barPackage.pricePerPerson * wedding.guestCount 
          });
        }
      }

      // Logistics
      if (logistics) {
        if (logistics.transportation?.guestTransfer) {
          budgetSheet.addRow({ 
            category: 'Logistics', 
            item: 'Transportation', 
            cost: logistics.transportation.guestTransfer.cost 
          });
        }
        if (logistics.baraat) {
          budgetSheet.addRow({ category: 'Logistics', item: 'Baraat', cost: 
            (logistics.baraat.ghodiCost || 0) + 
            (logistics.baraat.dholiCost || 0) + 
            (logistics.baraat.sfxCost || 0) 
          });
        }
        if (logistics.accommodation) {
          budgetSheet.addRow({ category: 'Logistics', item: 'Accommodation', cost: logistics.accommodation.totalCost });
        }
      }

      // Total Row
      budgetSheet.addRow({});
      budgetSheet.addRow({ category: 'TOTAL', item: 'Overall Budget', cost: wedding.totalBudget?.total || 0 });

      // Guest List Sheet
      const guestSheet = workbook.addWorksheet('Guest List');
      guestSheet.columns = [
        { header: 'Name', key: 'name', width: 30 },
        { header: 'Category', key: 'category', width: 15 },
        { header: 'RSVP Status', key: 'rsvp', width: 15 },
        { header: 'Dietary', key: 'dietary', width: 15 },
        { header: 'Phone', key: 'phone', width: 15 }
      ];

      guests.forEach(guest => {
        guestSheet.addRow({
          name: guest.name,
          category: guest.category,
          rsvp: guest.rsvpStatus,
          dietary: guest.dietaryPreference,
          phone: guest.phone
        });
      });

      return workbook;
    } catch (error) {
      throw error;
    }
  }

  formatCurrency(amount) {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount);
  }
}

export default new ReportService();